import { createRouter } from "@tanstack/react-router";
// This file is auto-generated by TanStack Router Vite plugin.
// Run `pnpm routes` or start the dev server to generate it.
import { routeTree } from "./routeTree.gen";

export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  scrollRestoration: true,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
